Add AccessControl to ModifyServiceUserRequest
aiven/aiven-go-client pull request #129
Opened 2021-09-02 14:01 UTC by BellionBastien

This PR adds missing field to the ModifyServiceUserRequest, allowing to update Redis user AccessControl.

2021-09-02 15:01 UTC, BellionBastien commented
Just also adde Postgres PostgresAllowReplication field to AccessControl struct

2021-09-03 09:28 UTC, alxric approved these changes
LGTM, ping @ivan-savciuc if you just want to double check

2021-09-03 09:56 UTC, mhoffm-aiven commented
Hey @BellionBastien

First of all thanks for the PR!

Secondly: since we now have `AccessControl` and the credential fields, could we make sure that the operation matches the payload? I'm thinking of validating that the operation is `set-access-control` when the `AccessControlPointer` is not `nil`. and `reset-credentials` when we have a `new_password`/`authentication` field. That way we can prevent accidential malformed payloads. Could we also `consts` for the operations?

2021-09-03 09:57 UTC, mhoffm-aiven requested changes
as commented here: https://github.com/aiven/aiven-go-client/pull/129#issuecomment-912415430

2021-09-03 10:50 UTC, mhoffm-aiven approved these changes
looks good to me

2021-09-03 11:00 UTC, merged

2021-09-03 11:01 UTC, ivan-savciuc commented
@BellionBastien, thanks for contributing