Make username an optional field on ConnectionPool requests
aiven/aiven-go-client pull request #134
Opened 2021-09-21 23:49 UTC by gandelman-a

This is currently a required field on the request structs while the API
does not require it.  Omitting it results in the pool using the
'Reuse inbound user', like the UI defaults to.

2021-09-21 23:59 UTC, cyx reviewed
👌

2021-09-22 07:24 UTC, ivan-savciuc requested changes
@gandelman-a, thanks for contributing. We have to use `*string` for optional fields. This is how Aiven API works: If the field is optional, it should not be set in the API Request.

2021-09-22 07:24 UTC, ivan-savciuc commented on connection_pool.go
> +		Username string `json:"username,omitempty"`
Please convert `string` to `*string`

2021-09-22 16:18 UTC, ivan-savciuc approved these changes
LGTM

2021-09-22 16:22 UTC, merged