Remove omitempty in order to permit update with empty values
aiven/aiven-go-client pull request #233
Opened 2022-12-07 10:14 UTC by Galiley

The API already handle empty and null values

2022-12-07 10:38 UTC, Serpentiel commented
hey, @Galiley! 👋

thank you for your contribution!

could you please elaborate a bit further, why would you want to send empty/nil values to the API anyway?

2022-12-07 10:44 UTC, Galiley commented
I want to send empty/null values to the API in order to remove for instance all the channels ACL for a certain user. This option is available in the Aiven Console

2022-12-07 13:20 UTC, Serpentiel commented
thanks! I will have to evaluate whether there are potential problems which could be caused by this change, particularly in other Aiven products that are dependent on this library, I will get back to you soon

2022-12-08 09:34 UTC, Serpentiel commented
afaik `omitempty` was supposed to introduce a similar behavior

2022-12-08 09:41 UTC, Galiley commented
Quoted from the documentation of [json.Marshal](https://pkg.go.dev/encoding/json#Marshal)
> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string. 

Empty slice, array or map is not encoded with omitempty which are supported by the Aiven API

2022-12-08 13:34 UTC, Serpentiel requested changes
this PR introduces no misbehavior for the dependent projects, although there are some changes that would be neat to have

2022-12-08 13:34 UTC, Serpentiel commented on service_user.go
> +func (ac AccessControl) MarshalJSON() ([]byte, error) {
please comment what this function does

2022-12-08 13:34 UTC, Serpentiel commented on service_user_test.go
> +func TestAccessControlMarshalJSON(t *testing.T) {
please make the use of `testing.T` as we do in the other tests

2022-12-09 15:43 UTC, Serpentiel approved these changes
lgtm

2022-12-09 16:21 UTC, merged