feat(client): flink application support
aiven/aiven-go-client pull request #252
Opened 2023-02-02 17:26 UTC by Serpentiel

adds support for Flink Application

2023-02-02 18:47 UTC, mhoffm-aiven commented on api.go
> +type UpdationSignatures struct {
Would go with `UpdateSignatures` maybe

2023-02-02 18:49 UTC, mhoffm-aiven commented
Is there no schema currently for the `interface{}` values?

2023-02-03 13:12 UTC, Serpentiel commented
> Is there no schema currently for the `interface{}` values?

there is, there are no plans to work with that schema in our IaaC tools, this could be added in future if there is need for it, but this is quite urgent at the moment

2023-02-03 14:07 UTC, ivan-savciuc requested changes
Nitpicking: some style related comments otherwise LGTM

2023-02-03 14:07 UTC, ivan-savciuc commented on api.go
> +type Identifiable struct {
Can we make a Flink similar to all the other API wrappers? 
Moreover something like this: 
```
CreateFlinkApplicationRequest{
		Nameable: Nameable{
			Name: name.
		},
	}
```
does not look good  at all.

2023-02-03 14:07 UTC, ivan-savciuc commented on flink_application.go
> +
I this these new line break is no necessary here between two connected statements

2023-02-03 14:32 UTC, ivan-savciuc approved these changes
LGTM

2023-02-03 14:32 UTC, merged