feat(service): expose tech_emails in Service
aiven/aiven-go-client pull request #319
Opened 2023-12-13 08:28 UTC by jeff-held-aiven

2023-12-13 11:59 UTC, Serpentiel commented on service_test.go
> +var servicesHandler = &ServicesHandler{
I'm not sure if this is a good idea, with this approach it's possible to use `servicesHandler` in other tests as well, which might be unexpected, WDYT?

2023-12-13 12:03 UTC, byashimov requested changes

2023-12-13 12:03 UTC, byashimov commented on service.go
>  	}
Hey. Nil is not a value here, so no need to be a pointer for the slice.

2023-12-13 12:03 UTC, byashimov commented on service_test.go
> +	})
Please do not refactor the client. It will be replaced soon with code-generated one.

2023-12-21 13:27 UTC, byashimov approved these changes
lgtm

2023-12-21 13:28 UTC, merged